### ISSUE TITLE
Logo Design Offering as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [Arquisoft/sole_chat#79]
Hello Sir. I'm a Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks for the attention.

**Comment by emiliocortina** [comment]
Hi! 
I'm sorry to inform you that we already have a product image and design guidelines so there's no help needed in that aspect.
However, we'd gladly appreciate if you want to contribute in any other issue regarding the application's development. 
Have a nice day! 😊
